### ISSUE TITLE
Can this sim plugin offer an API to count ringing times and even record a calling?

### ISSUE THREAD

**Issue by gloCalHelp** [pbakondy/cordova-plugin-sim#1]
Dear Peter, 

     Thank you for offer this plugin, can this sim plugin offer an API to count ringing times and even record a calling? 
   
      It would be my  honor that if you could send this reply to me to mail: jiaxinlin@live.com

Bye.

**Comment by pbakondy** [comment]
I think counting the ringing times is not possible in any way.
The waiting sound can be different in every provider, you can not "count" this.

Recording a call - it is possible, if somebody writes the background interface to the core system API.
I am not planning to do this.
