### ISSUE TITLE
Not  reading AT&T SIM

### ISSUE THREAD

**Issue by azn1viet** [pbakondy/cordova-plugin-sim#10]
I got Verizon and AT&T in US, and airtel in India. It can read Verizon, airtel but not AT&T. I don't have other carriers to test with like T-mobile, Sprint, etc.. So do you think AT&T block the SIM reading data via Cordova?

**Comment by pbakondy** [comment]
How do you mean you can not read AT&T?

**Comment by azn1viet** [comment]
var dataCarrier = result['carrierName'];

dataCarrier gives me Verizon, airtel (India) but when I plug AT&T SIM in, it gave me nothing, blank, no value.

**Comment by pbakondy** [comment]
Yes, the provider may block reading this data. This is an OS-level function I can not fix it.

Maybe you could try restart your phone.
