### ISSUE TITLE
Empty window.plugins within Phonegap Developer App

### ISSUE THREAD

**Issue by einicher** [pbakondy/cordova-plugin-sim#12]
I did `cordova plugin add cordova-plugin-sim` and it was successfully installed without any errors.

But inside my project `window.plugins.sim` does not exist.

There is only a `window.plugins.insomnia` which seems to be empty.

Do i have to add some other configuration?

**Comment by pbakondy** [comment]
No other configuration needed.
The object should exist, I could not reproduce the error.
What is your environment? Android / iOS?

**Comment by einicher** [comment]
It works when i run the app with Android Studio on my phone and in the released apk it works fine too.
It just does not work with `phonegap serve` and the Phonegap Android Developer App (wich is very practical, except a missing JavaScript debugger). Other plugins like sim do not work too there.
One of many unnecessary problems you get into when you start with phonegap :/

**Comment by pbakondy** [comment]
Why are you expecting to have sim data when you run your app in browser?
Do a platform check and use it only on Android.

**Comment by einicher** [comment]
Not in browser, it runs on the phone within Phonegap Developer App.
Some plugins work (like access phone contacts) and some do not.

**Comment by pbakondy** [comment]
Can you tell me what is the return value of the cordova device plugin?

**Comment by einicher** [comment]
[phonegap] [console.log] { available: true,
  platform: 'Android',
  version: '5.1.1',
  uuid: 'aaa57b0bf3ed728',
  cordova: '4.1.1',
  model: 'SM-G903F',
  manufacturer: 'samsung' }

**Comment by pbakondy** [comment]
This plugin will not work with PhoneGap Developer App. There is a predefined list of supported plugins for this tester application: http://docs.phonegap.com/references/developer-app/troubleshoot-faq/

> If you're using a plugin in your project that is not shown in this list, it will not work with the PhoneGap Developer App out of the box. However, you can create your own custom build of the PhoneGap Developer app locally and include any other plugins there. We recommend always checking for the existence of any plugin in your code first before using it to avoid errors in testing in general.

If you are using `PhoneGap CLI` I would recommend using the following commands (requires connecting your device with USB cable):

```
phonegap platform add android
phonegap run android
```

**Comment by einicher** [comment]
The run android is not working with usb but usb is working with android studio.
big thanx for your explanations!
