### ISSUE TITLE
Roaming detection in iOS

### ISSUE THREAD

**Issue by BhavanPatel** [pbakondy/cordova-plugin-sim#13]
Hey, @pbakondy 
I am not able to detect roaming in iOS like android.
is there any way to detect roaming in iOS?

http://stackoverflow.com/questions/900547/is-there-any-way-to-determine-if-the-iphone-is-roaming

this link have some iOS code to detect but don't know how to use it can you please configure in plugin ?

**Comment by pbakondy** [comment]
There is no API that will allow you to detect if the user is roaming. Also the tutorial you point to is for jailbroken devices. It will not work on an Appstore app.

http://stackoverflow.com/a/22036792

I use only documented features because it is guaranteed to work.

**Comment by pallaviMN** [comment]
@BhavanPatel , finally were you able to check roaming status in iOS? If yes, how did you achieve it?
