### ISSUE TITLE
phoneNumber format

### ISSUE THREAD

**Issue by sariyu** [pbakondy/cordova-plugin-sim#15]
It is working fine, but it is very useful to get phone number separete and country code separate. Is it possible to do that ?

**Comment by pbakondy** [comment]
You can get them separately with `result.phoneNumber` and `result.countryCode`

**Comment by sariyu** [comment]
result.phoneNumber gives result like +91xxxxxxxxxx for some networks and xxxxxxxxxx for other networks of same country. pbakondy i'm developing ionic cordova app, could you please share any working logic or code on showing the user with contacts of those who already have installed the same app like whats app / telegram.

**Comment by sariyu** [comment]
result.phoneNumber gives result like +91xxxxxxxxxx for some networks and xxxxxxxxxx for other networks of same country. pbakondy i'm developing ionic cordova app, could you please share any working logic or code on showing the user with contacts of those who already have installed the same app like whats app / telegram.

**Comment by pbakondy** [comment]
I would suggest using the following library to unify the different phonenumber formats: https://www.npmjs.com/package/google-libphonenumber

I don't know any existing solution for "showing the user with contacts of those who already have installed the same app"
