### ISSUE TITLE
Android 6.0

### ISSUE THREAD

**Issue by thari911** [pbakondy/cordova-plugin-sim#16]
Hi. I use this plugin and it was working fine until i tested on an Android 6.0 device. It's always returning the error callback. Can you please help me fix this.

Thanks.

**Comment by pbakondy** [comment]
Hi,

I found the reason of your error:

> If the device is running Android 6.0 or higher, and your app's target SDK is 23 or higher: The app has to list the permissions in the manifest, and it must request each dangerous permission it needs while the app is running.

( from http://developer.android.com/training/permissions/requesting.html )

I am working on the solution

**Comment by pbakondy** [comment]
Please check latest release
