### ISSUE TITLE
didnt work on iphone6+

### ISSUE THREAD

**Issue by mohamedzaher88** [pbakondy/cordova-plugin-sim#17]
hello,

i use this code

document.addEventListener("deviceready", onDeviceReady, false);

function onDeviceReady() {
  window.plugins.sim.getSimInfo(successCallback, errorCallback);
}

function successCallback(result) {
  alert(result);
}

function errorCallback(error) {
  alert(error);
}

alert [ object object ]

what is the problem ?????

**Comment by pbakondy** [comment]
Return variable is an object. Window.alert() transforms the parameter to String. 
Any object transformed to string is "[object Object]"
Please try to learn some basic JavaScript before raising issues.

**Comment by mohamedzaher88** [comment]
Can you help me and post full example

**Comment by pbakondy** [comment]
Sorry, I don't have time to give JavaScript lessons.

Try to start here: 
- https://github.com/javascript-society/javascript-path
- https://github.com/ericelliott/essential-javascript-links

**Comment by mohamedzaher88** [comment]
thanks

**Comment by juanpablogd** [comment]
function successCallback(result) {
       //get carrierName
        var carrierNameoperador = result.carrierName;
       // other variable....
    }
