### ISSUE TITLE
window.plugins

### ISSUE THREAD

**Issue by velorias** [pbakondy/cordova-plugin-sim#18]
When I`m calling window.plugins.sim.get...., it says that windows.plugins undefined

**Comment by pbakondy** [comment]
cordova version?
android / ios?
what command are you using?
emulator / device?
ionic / phonegap / etc?

**Comment by velorias** [comment]
I`m sorry, my mistake. It`s just was a difference bitween our index.js files. Mine is in the app object. Never mind. Thank you for reply anyway)

**Comment by Grandt** [comment]
@velorias please elaborate on what was wrong. I'm new to Ionic and this issue is driving me up a wall.
