### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by madhusvce07** [pbakondy/cordova-plugin-sim#19]
I am unable to build once i add the plugin and the code as java script in HTML file.

index.html

	<html>
	<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta http-equiv='Content-Type' content='text/html;charset=UTF-8' />
	<script>
			document.addEventListener("deviceready", onDeviceReady, false);		
			function onDeviceReady() {
				window.plugins.sim.getSimInfo(successCallback, errorCallback);
			}
			function successCallback(result) {
				sap.m.MessageToast.show(result);
			}
			function errorCallback(error) {
				sap.m.MessageToast.show(error);
			}
	</script>
	</head>
	<body>
		<div id="deviceready"></div>
	</body>
	</html>

The error i get is :
ERROR building one of the platforms: Error code 1 for command: cmd with args: /s
,/c,"C:\Users\....\platforms\android\gradlew cdvBuildDebug -b C:\Users\....\platforms\android\build.gradle -
Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"
You may not have the required environment or OS to build this project
Error: Error code 1 for command: cmd with args: /s,/c,"C:\Users\....\platforms\android\gradlew
 cdvBuildDebug -b C:\Users\....\platforms\android\build.gradle -Dorg.gradle.daemon=true -Pandr
oid.useDeprecatedNdk=true"

**Comment by pbakondy** [comment]
Are you able to build without this plugin?
Are you able to build with an official cordova plugin like cordova-plugin-device?

**Comment by madhusvce07** [comment]
Yes i am able to build without this plugin and with cordova-plugin-device.

**Comment by pbakondy** [comment]
Then you should extend the working version with codes related to this plugin.
For example the html code above misses the cordova.js reference.

BTW the error message is related to the build process not the plugin itself.
It is like you do not have AndroidSDK installed for Android build.
Please check Android platform requirements listed in this page:
https://cordova.apache.org/docs/en/6.x/guide/platforms/android/index.html
