### ISSUE TITLE
cordova build android problems

### ISSUE THREAD

**Issue by DieguitoBueno** [pbakondy/cordova-plugin-sim#22]
### Expected behaviour
The build to run properly with this plugin

### Actual behaviour
As soon as I install this plugin, the cordova build command doesn't build anymore

### I'm seeing this behaviour on
_Remove this hint: these checkboxes can be checked like this: [x]_
- [ ] iOS device
- [ ] iOS simulator
- [ ] Android device
- [ ] Android emulator
- [x] Android builder

### I am using
- [x] cordova
- [ ] ionic
- [ ] PhoneGap
- [ ] PhoneGap Developer App
- [ ] Intel XDK
- [ ] Intel App Preview
- [ ] Telerik
- [ ] Other:

### I've checked these
- [ ] It happens on a fresh Cordova CLI project as well.
- [ ] I'm waiting for `deviceready` to fire.
- [ ] My JavaScript has no errors (`window.onerror` catches nothing).
- [x] I'm using the latest cordova library, Android SDK, Xcode, etc.

### So how can we reproduce this?
C:\Axxiome\Development\eclipse64\Workspace64\XXX_PROJ>cordova build andr
oid
Running command: cmd "/s /c "C:\Axxiome\Development\eclipse64\Workspace64\XXX_PROJ\platforms\android\cordova\build.bat""
ANDROID_HOME=C:\Users\dce\android-sdks
JAVA_HOME=C:\Progra~1\Java\jdk1.8.0_60
Running: C:\Axxiome\Development\eclipse64\Workspace64\XXX_PROJ\platforms
\android\gradlew cdvBuildDebug -b C:\Axxiome\Development\eclipse64\Workspace64\XXX_PROJ\platforms\android\build.gradle -Dorg.gradle.daemon=true

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.android.support:support-v4:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/maven-met
adata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v4/
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

**Comment by pbakondy** [comment]
Did you install Android Support Library from Android SDK?

**Comment by DieguitoBueno** [comment]
Hi @pbakondy , no.. Sorry, but for all the plugins I have so far I did not need to use it..
Every build until now were ok.
When I add this plugin to the project, I'm facing errors :(

**Comment by pbakondy** [comment]
Try install this dependency and let's see if it is fixed.

**Comment by DieguitoBueno** [comment]
I've just updated my Android Support Library in SDK
and installed the plugin cordova-plugin-android-support-v4
No success building the app so far :(

**Comment by pbakondy** [comment]
Could you list the installed plugins?

Could you please try to build a new cordova plugin with only this plugin?

From gradle message:
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

**Comment by DieguitoBueno** [comment]
Plugin List:
com.cordova.plugins.sms 0.1.8 "Cordova SMS Plugin"
cordova-plugin-android-support-v4 21.0.1 "Android Support v4"
cordova-plugin-device 1.1.1 "Device"
cordova-plugin-file 4.1.1 "File"
cordova-plugin-http 0.2.0 "SSL Pinning"
cordova-plugin-sim 1.2.1 "SIM"
cordova-plugin-whitelist 1.1.0 "Whitelist"

**Comment by pbakondy** [comment]
BTW you don't need cordova-plugin-android-support-v4 because gradle should resolve and install this dependency.
Plz remove this plugin.

**Comment by DieguitoBueno** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.android.support:support-v4:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/maven-met
adata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v4/
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --de opt
ion to get more log output.

BUILD FAILED

Total time: 4.466 secs

**Comment by pbakondy** [comment]
What command did you run at last?
What is the plugin list?

**Comment by DieguitoBueno** [comment]
Hi, @pbakondy 
The list is 4 or 3 comments above..
The command is "cordova build android"

**Comment by pbakondy** [comment]
Please remove cordova-plugin-android-support-v4 and try again

**Comment by pbakondy** [comment]
Please try to build with only this plugin.

**Comment by DieguitoBueno** [comment]
Hi @pbakondy in the plugin list, this plugin was not there anymore.. it was already removed.
The build command was after that

**Comment by DieguitoBueno** [comment]
Ok, I'll try it

**Comment by DieguitoBueno** [comment]
new project created.. 
Plugin added, Platform added. 
Build failed

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.android.support:support-v4:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/maven-met
adata.xml
         https://repo1.maven.org/maven2/com/android/support/support-v4/
     Required by:
         :android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --de opt
ion to get more log output.

BUILD FAILED

**Comment by pbakondy** [comment]
Please try install these items of Android SDK and try again building the project

Android Support Repository
Android Support Library
Google Play Services
Google Repository

**Comment by pbakondy** [comment]
Can we close this issue?
