### ISSUE TITLE
IMEI for iOS

### ISSUE THREAD

**Issue by rzorzella** [pbakondy/cordova-plugin-sim#23]
### Expected behaviour
There is possible get IMEI from iPohone?

- [ X] iOS device
- [ ] iOS simulator
- [ ] Android device
- [ ] Android emulator

### I am using

- [X ] cordova
- [ ] ionic
- [ ] PhoneGap
- [ ] PhoneGap Developer App
- [ ] Intel XDK
- [ ] Intel App Preview
- [ ] Telerik
- [ ] Other:

**Comment by pbakondy** [comment]
http://stackoverflow.com/a/19927376
