### ISSUE TITLE
After Adding cordova.plugins.diagnostic" version="2.3.15" following Error Occurred see in comment

### ISSUE THREAD

**Issue by papular** [pbakondy/cordova-plugin-sim#24]
I tried to much googled a lot some suggestion suggest that set android  SDK version i have checked its fine which is as follows:-
 <preference name="android-minSdkVersion" value="19" />
  <preference name="android-maxSdkVersion" value="22" />
  <preference name="android-targetSdkVersion" value="22" />
What is the problem , its take my whole day actually to resolve but not found any solution....

1>------ Build started: Project: Meradriver, Configuration: Debug Android ------
1>  Your environment has been set up for using Node.js 0.12.2 (ia32) and npm.
1>  ------ Ensuring correct global installation of package from source package directory: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\APACHECORDOVATOOLS\packages\vs-tac
1>  ------ Name from source package.json: vs-tac
1>  ------ Version from source package.json: 1.0.34
1>  ------ Package already installed globally at correct version.
1>  ------ Cordova tools 6.1.1 already installed.
1>  ------ Build Settings:
1>  ------ Build Settings:
1>  ------    platformConfigurationBldDir: D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\bld\Android\Debug
1>  ------    platformConfigurationBinDir: D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\bin\Android\Debug
1>  ------    buildCommand: build
1>  ------    platform: Android
1>  ------    cordovaPlatform: android
1>  ------    configuration: Debug
1>  ------    cordovaConfiguration: Debug
1>  ------    projectName: Meradriver
1>  ------    projectSourceDir: D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver
1>  ------    npmInstallDir: C:\Users\skylabs\AppData\Roaming\npm
1>  ------    buildTarget: AndroidEmulator
1>  ------    language: en-US
1>  ------ Platform android already exists
1>  ------ Copying native files from D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\res\native\android to platforms\android
1>  ------ Done copying native files to platforms\android
1>  ------ Updating plugins
1>  ------ Currently installed plugins: cordova-plugin-whitelist@1.2.1,cordova-plugin-geolocation@2.1.0,cordova-plugin-network-information@1.2.0,cordova-plugin-inappbrowser@1.3.0,cordova-plugin-device-orientation@1.0.2,cordova-plugin-x-toast@2.5.0,cordova.plugins.diagnostic@2.3.15
1>  ------ Currently installed dependent plugins:
1>  ------ Currently configured plugins:
1>  ------ Preparing platform: android
1>  Executing "before_prepare"  hook for all plugins.
1>  Executing "before_build"  hook for all plugins.
1>   Using this version of Cordova with older version of cordova-android is being deprecated. Consider upgrading to cordova-android@5.0.0 or newer.
1>  Searching PlatformJson files for differences between project vs. platform installed plugins
1>  No differences found between project and android platform. Continuing...
1>  Generating config.xml from defaults for platform "android"
1>  Wrote out Android application name to "Meradriver"
1>  deleted: D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-land-hdpi\screen.png
1>  deleted: D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-land-ldpi\screen.png
1>  deleted: D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-land-mdpi\screen.png
1>  deleted: D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-land-xhdpi\screen.png
1>  deleted: D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-port-hdpi\screen.png
1>  deleted: D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-port-ldpi\screen.png
1>  deleted: D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-port-mdpi\screen.png
1>  deleted: D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-port-xhdpi\screen.png
1>  splash screens: [{"src":"res/screens/android/screen-hdpi-landscape.png","density":"land-hdpi","platform":null},{"src":"res/screens/android/screen-ldpi-landscape.png","density":"land-ldpi","platform":null},{"src":"res/screens/android/screen-mdpi-landscape.png","density":"land-mdpi","platform":null},{"src":"res/screens/android/screen-xhdpi-landscape.png","density":"land-xhdpi","platform":null},{"src":"res/screens/android/screen-hdpi-portrait.png","density":"port-hdpi","platform":null},{"src":"res/screens/android/screen-ldpi-portrait.png","density":"port-ldpi","platform":null},{"src":"res/screens/android/screen-mdpi-portrait.png","density":"port-mdpi","platform":null},{"src":"res/screens/android/screen-xhdpi-portrait.png","density":"port-xhdpi","platform":null}]
1>  copying image from D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\res\screens\android\screen-hdpi-landscape.png to D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-land-hdpi\screen.png
1>  copying image from D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\res\screens\android\screen-ldpi-landscape.png to D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-land-ldpi\screen.png
1>  copying image from D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\res\screens\android\screen-mdpi-landscape.png to D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-land-mdpi\screen.png
1>  copying image from D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\res\screens\android\screen-xhdpi-landscape.png to D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-land-xhdpi\screen.png
1>  copying image from D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\res\screens\android\screen-hdpi-portrait.png to D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-port-hdpi\screen.png
1>  copying image from D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\res\screens\android\screen-ldpi-portrait.png to D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-port-ldpi\screen.png
1>  copying image from D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\res\screens\android\screen-mdpi-portrait.png to D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-port-mdpi\screen.png
1>  copying image from D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\res\screens\android\screen-xhdpi-portrait.png to D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-port-xhdpi\screen.png
1>  deleted: D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-hdpi\icon.png
1>  deleted: D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-ldpi\icon.png
1>  deleted: D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-mdpi\icon.png
1>  deleted: D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-xhdpi\icon.png
1>  copying image from D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\res\icons\android\icon-36-ldpi.png to D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-ldpi\icon.png
1>  copying image from D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\res\icons\android\icon-48-mdpi.png to D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-mdpi\icon.png
1>  copying image from D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\res\icons\android\icon-72-hdpi.png to D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-hdpi\icon.png
1>  copying image from D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\res\icons\android\icon-96-xhdpi.png to D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\res\drawable-xhdpi\icon.png
1>  Wrote out Android package name to "meradriver.mobileapp"
1>  Executing "after_prepare"  hook for all plugins.
1>  ------ Copied D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\bin\Android\Debug\VSBuildInfo.xml to platforms\android\assets\www\VSBuildInfo.xml
1>  ------ Building platform: android
1>  Debug
1>  ------ Build configuration options: --debug
1>  Executing "before_compile"  hook for all plugins.
1>  Running command: cmd "/s /c ""D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\cordova\build.bat" --debug "--buildConfig=D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\build.json"""
1>  ANDROID_HOME=C:\Program Files (x86)\Android\android-sdk
1>  JAVA_HOME=C:\Program Files (x86)\Java\jdk1.7.0_55
1>  Reading build config file: D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\build.json
1>  Running: D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\gradlew cdvBuildDebug -b D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\build.gradle -Dorg.gradle.daemon=true
1>  :preBuild
1>  :compileDebugNdk
1>  :preDebugBuild
1>  :checkDebugManifest
1>  :CordovaLib:compileLint
1>  :CordovaLib:copyDebugLint UP-TO-DATE
1>  :CordovaLib:mergeDebugProguardFiles UP-TO-DATE
1>  :CordovaLib:preBuild
1>  :CordovaLib:preDebugBuild
1>  :CordovaLib:checkDebugManifest
1>  :CordovaLib:prepareDebugDependencies
1>  :CordovaLib:compileDebugAidl
1>  :CordovaLib:compileDebugRenderscript
1>  :CordovaLib:generateDebugBuildConfig
1>  :CordovaLib:generateDebugAssets UP-TO-DATE
1>  :CordovaLib:mergeDebugAssets
1>  :CordovaLib:generateDebugResValues UP-TO-DATE
1>  :CordovaLib:generateDebugResources
1>  :CordovaLib:packageDebugResources
1>  :CordovaLib:processDebugManifest
1>  :CordovaLib:processDebugResources
1>  :CordovaLib:generateDebugSources
1>  Note: Some input files use or override a deprecated API.
1>  Note: Recompile with -Xlint:deprecation for details.
1>  :CordovaLib:compileDebugJava
1>  :CordovaLib:processDebugJavaRes UP-TO-DATE
1>  :CordovaLib:packageDebugJar
1>  :CordovaLib:compileDebugNdk
1>  :CordovaLib:packageDebugJniLibs UP-TO-DATE
1>  :CordovaLib:packageDebugLocalJar UP-TO-DATE
1>  :CordovaLib:packageDebugRenderscript UP-TO-DATE
1>  :CordovaLib:bundleDebug
1>  :prepareAndroidCordovaLibUnspecifiedDebugLibrary
1>  :preReleaseBuild
1>  :CordovaLib:copyReleaseLint UP-TO-DATE
1>  :CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
1>  :CordovaLib:preReleaseBuild
1>  :CordovaLib:checkReleaseManifest
1>  :CordovaLib:prepareReleaseDependencies
1>  :CordovaLib:compileReleaseAidl
1>  :CordovaLib:compileReleaseRenderscript
1>  :CordovaLib:generateReleaseBuildConfig
1>  :CordovaLib:generateReleaseAssets UP-TO-DATE
1>  :CordovaLib:mergeReleaseAssets
1>  :CordovaLib:generateReleaseResValues UP-TO-DATE
1>  :CordovaLib:generateReleaseResources
1>  :CordovaLib:packageReleaseResources
1>  :CordovaLib:processReleaseManifest
1>  :CordovaLib:processReleaseResources
1>  :CordovaLib:generateReleaseSources
1>  Note: Some input files use or override a deprecated API.
1>  Note: Recompile with -Xlint:deprecation for details.
1>  :CordovaLib:compileReleaseJava
1>  :CordovaLib:processReleaseJavaRes UP-TO-DATE
1>  :CordovaLib:packageReleaseJar
1>  :CordovaLib:compileReleaseNdk
1>  :CordovaLib:packageReleaseJniLibs UP-TO-DATE
1>  :CordovaLib:packageReleaseLocalJar UP-TO-DATE
1>  :CordovaLib:packageReleaseRenderscript UP-TO-DATE
1>  :CordovaLib:bundleRelease
1>  :prepareComAndroidSupportAnimatedVectorDrawable2321Library
1>  :prepareComAndroidSupportAppcompatV72321Library
1>  :prepareComAndroidSupportSupportV42321Library
1>  :prepareComAndroidSupportSupportVectorDrawable2321Library
1>  :prepareDebugDependencies
1>  :compileDebugAidl
1>  :compileDebugRenderscript
1>  :generateDebugBuildConfig
1>  :generateDebugAssets UP-TO-DATE
1>  :mergeDebugAssets
1>  :generateDebugResValues UP-TO-DATE
1>  :generateDebugResources
1>  :mergeDebugResources
1>  :processDebugManifest
1>  D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\build\intermediates\res\debug\values-v23\values.xml:6: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
1>
1>  D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\build\intermediates\res\debug\values-v23\values.xml:35: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.
1>  :processDebugResources FAILED
1>
1>  BUILD FAILED
1>
1>  Total time: 16.058 secs
1>
1>
1>  FAILURE: Build failed with an exception.
1>
1>  * What went wrong:
1>  Execution failed for task ':processDebugResources'.
1>  > com.android.ide.common.internal.LoggedErrorException: Failed to run command:
1>  	C:\Program Files (x86)\Android\android-sdk\build-tools\23.0.3\aapt.exe package -f --no-crunch -I C:\Program Files (x86)\Android\android-sdk\platforms\android-22\android.jar -M D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\build\intermediates\manifests\full\debug\AndroidManifest.xml -S D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\build\intermediates\res\debug -A D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\build\intermediates\assets\debug -m -J D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\build\generated\source\r\debug -F D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\build\intermediates\res\resources-debug.ap_ --debug-mode --custom-package meradriver.mobileapp -0 apk --output-text-symbols D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\build\intermediates\symbols\debug
1>MDAVSCLI : error Code:
1>  	1
1>  Output:
1>  	D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\build\intermediates\res\debug\values-v23\values.xml:6: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
1>
1>  	D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\build\intermediates\res\debug\values-v23\values.xml:35: error: Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.
1>
1>
1>
1>  * Try:
1>  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
1>  Picked up _JAVA_OPTIONS: -Xmx512M
1>
1>  D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\cordova\node_modules\q\q.js:126
1>                      throw e;
1>                            ^
1>  Error code 1 for command: cmd with args: /s /c ""D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\gradlew" cdvBuildDebug -b "D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\build.gradle" -Dorg.gradle.daemon=true"
1>  Command finished with error code 1: cmd /s /c ""D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\platforms\android\cordova\build.bat" --debug "--buildConfig=D:\Skylabs Project\Live Projects\Meradriver\Mobile App\MeradriverApp\Meradriver\Meradriver\build.json""
1>MDAVSCLI : error : cmd: Command failed with exit code 1
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by pbakondy** [comment]
Works for me.
What is your environment?
Why are you sure that this plugin causes the build error?
What are the installed plugins?

```
$ cordova create testing
Creating a new cordova project.
$ cd testing/
$ cordova plugin add cordova-plugin-sim
Fetching plugin "cordova-plugin-sim" via npm
$ cordova plugin add cordova.plugins.diagnostic
Fetching plugin "cordova.plugins.diagnostic" via npm
$ cordova platform add android
Adding android project...
Creating Cordova project for the Android platform:
  Path: platforms/android
  Package: io.cordova.hellocordova
  Name: HelloCordova
  Activity: MainActivity
  Android target: android-23
Android project created with cordova-android@5.1.1
Installing "cordova-plugin-sim" for android
Installing "cordova.plugins.diagnostic" for android
Discovered plugin "cordova-plugin-whitelist" in config.xml. Installing to the project
Fetching plugin "cordova-plugin-whitelist@1" via npm
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
          
$ cordova build android
ANDROID_HOME=/usr/local/Cellar/android-sdk/24.4.1_1
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_65.jdk/Contents/Home
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:compileDebugAidl
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:prepareAndroidCordovaLibUnspecifiedDebugLibrary
:preReleaseBuild UP-TO-DATE
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:compileReleaseAidl
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareComAndroidSupportAnimatedVectorDrawable2330Library
:prepareComAndroidSupportAppcompatV72330Library
:prepareComAndroidSupportSupportV42400Alpha2Library
:prepareComAndroidSupportSupportVectorDrawable2330Library
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:compileDebugJavaWithJavacNote: /Users/user/Documents/20160422/testing/platforms/android/src/cordova/plugins/Diagnostic.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:compileDebugNdk UP-TO-DATE
:compileDebugSources
:transformClassesWithDexForDebug
:mergeDebugJniLibFolders
:transformNative_libsWithMergeJniLibsForDebug
:processDebugJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForDebug
:validateDebugSigning
:packageDebug
:zipalignDebug
:assembleDebug
:cdvBuildDebug

BUILD SUCCESSFUL

Total time: 1 mins 30.166 secs
Built the following apk(s): 
  /Users/user/Documents/20160422/testing/platforms/android/build/outputs/apk/android-debug.apk


```

**Comment by papular** [comment]
1)-I have used Visual Studio 2015 for Developing Cordova Projects.

2)-​
because when i added Diagnostic plugin it through the error when i remove
diagnostic plugin error resolve but i need diagnostic plugin in my project
​.

3)- I have used following plugins:-Network/In App Browser/Geolocation
​​


On Apr 22, 2016 20:00, "Peter Bakondy" <notifications@github.com> wrote:
>
> Works for me.
> What is your environment?
> Why are you sure that this plugin causes the build error?
> What are the installed plugins?
>
> $ cordova create testing
> Creating a new cordova project.
> $ cd testing/
> $ cordova plugin add cordova-plugin-sim
> Fetching plugin "cordova-plugin-sim" via npm
> $ cordova plugin add cordova.plugins.diagnostic
> Fetching plugin "cordova.plugins.diagnostic" via npm
> $ cordova platform add android
> Adding android project...
> Creating Cordova project for the Android platform:
>   Path: platforms/android
>   Package: io.cordova.hellocordova
>   Name: HelloCordova
>   Activity: MainActivity
>   Android target: android-23
> Android project created with cordova-android@5.1.1
> Installing "cordova-plugin-sim" for android
> Installing "cordova.plugins.diagnostic" for android
> Discovered plugin "cordova-plugin-whitelist" in config.xml. Installing to
the project
> Fetching plugin "cordova-plugin-whitelist@1" via npm
> Installing "cordova-plugin-whitelist" for android
>
>                This plugin is only applicable for versions of
cordova-android greater than 4.0. If you have a previous platform version,
you do *not* need this plugin since the whitelist will be built in.
>
> $ cordova build android
> ANDROID_HOME=/usr/local/Cellar/android-sdk/24.4.1_1
> JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_65.jdk/Contents/Home
> :preBuild UP-TO-DATE
> :preDebugBuild UP-TO-DATE
> :checkDebugManifest
> :CordovaLib:preBuild UP-TO-DATE
> :CordovaLib:preDebugBuild UP-TO-DATE
> :CordovaLib:compileDebugNdk UP-TO-DATE
> :CordovaLib:compileLint
> :CordovaLib:copyDebugLint UP-TO-DATE
> :CordovaLib:mergeDebugProguardFiles
> :CordovaLib:packageDebugRenderscript UP-TO-DATE
> :CordovaLib:checkDebugManifest
> :CordovaLib:prepareDebugDependencies
> :CordovaLib:compileDebugRenderscript
> :CordovaLib:generateDebugResValues
> :CordovaLib:generateDebugResources
> :CordovaLib:packageDebugResources
> :CordovaLib:compileDebugAidl
> :CordovaLib:generateDebugBuildConfig
> :CordovaLib:generateDebugAssets UP-TO-DATE
> :CordovaLib:mergeDebugAssets
> :CordovaLib:processDebugManifest
> :CordovaLib:processDebugResources
> :CordovaLib:generateDebugSources
> :CordovaLib:compileDebugJavaWithJavacNote: Some input files use or
override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
>
> :CordovaLib:processDebugJavaRes UP-TO-DATE
> :CordovaLib:transformResourcesWithMergeJavaResForDebug
> :CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
> :CordovaLib:mergeDebugJniLibFolders
> :CordovaLib:transformNative_libsWithMergeJniLibsForDebug
> :CordovaLib:transformNative_libsWithSyncJniLibsForDebug
> :CordovaLib:bundleDebug
> :prepareAndroidCordovaLibUnspecifiedDebugLibrary
> :preReleaseBuild UP-TO-DATE
> :CordovaLib:preReleaseBuild UP-TO-DATE
> :CordovaLib:compileReleaseNdk UP-TO-DATE
> :CordovaLib:copyReleaseLint UP-TO-DATE
> :CordovaLib:mergeReleaseProguardFiles
> :CordovaLib:packageReleaseRenderscript UP-TO-DATE
> :CordovaLib:checkReleaseManifest
> :CordovaLib:prepareReleaseDependencies
> :CordovaLib:compileReleaseRenderscript
> :CordovaLib:generateReleaseResValues
> :CordovaLib:generateReleaseResources
> :CordovaLib:packageReleaseResources
> :CordovaLib:compileReleaseAidl
> :CordovaLib:generateReleaseBuildConfig
> :CordovaLib:generateReleaseAssets UP-TO-DATE
> :CordovaLib:mergeReleaseAssets
> :CordovaLib:processReleaseManifest
> :CordovaLib:processReleaseResources
> :CordovaLib:generateReleaseSources
> :CordovaLib:compileReleaseJavaWithJavacNote: Some input files use or
override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
>
> :CordovaLib:processReleaseJavaRes UP-TO-DATE
> :CordovaLib:transformResourcesWithMergeJavaResForRelease
> :CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
> :CordovaLib:mergeReleaseJniLibFolders
> :CordovaLib:transformNative_libsWithMergeJniLibsForRelease
> :CordovaLib:transformNative_libsWithSyncJniLibsForRelease
> :CordovaLib:bundleRelease
> :prepareComAndroidSupportAnimatedVectorDrawable2330Library
> :prepareComAndroidSupportAppcompatV72330Library
> :prepareComAndroidSupportSupportV42400Alpha2Library
> :prepareComAndroidSupportSupportVectorDrawable2330Library
> :prepareDebugDependencies
> :compileDebugAidl
> :compileDebugRenderscript
> :generateDebugBuildConfig
> :generateDebugAssets UP-TO-DATE
> :mergeDebugAssets
> :generateDebugResValues
> :generateDebugResources
> :mergeDebugResources
> :processDebugManifest
> :processDebugResources
> :generateDebugSources
> :compileDebugJavaWithJavacNote:
/Users/user/Documents/20160422/testing/platforms/android/src/cordova/plugins/Diagnostic.java
uses unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
>
> :compileDebugNdk UP-TO-DATE
> :compileDebugSources
> :transformClassesWithDexForDebug
> :mergeDebugJniLibFolders
> :transformNative_libsWithMergeJniLibsForDebug
> :processDebugJavaRes UP-TO-DATE
> :transformResourcesWithMergeJavaResForDebug
> :validateDebugSigning
> :packageDebug
> :zipalignDebug
> :assembleDebug
> :cdvBuildDebug
>
> BUILD SUCCESSFUL
>
> Total time: 1 mins 30.166 secs
> Built the following apk(s):
>
/Users/user/Documents/20160422/testing/platforms/android/build/outputs/apk/android-debug.apk

**Comment by papular** [comment]
@pbakondy Please update ...

**Comment by pbakondy** [comment]
"because when i added Diagnostic plugin it through the error when i remove diagnostic plugin error resolve but i need diagnostic plugin in my project"

It looks like the problem source is the diagnostic plugin not the sim plugin.

I googled your error message and I found this page:
http://stackoverflow.com/questions/32075498/error-retrieving-parent-for-item-no-resource-found-that-matches-the-given-name

If it does not work go to the diagnostic plugin site.
