### ISSUE TITLE
phoneNumber property is empty

### ISSUE THREAD

**Issue by mladenp** [pbakondy/cordova-plugin-sim#25]
### Expected behaviour
phoneNumber should return my phone number

### Actual behaviour
It returns empty string

### I'm seeing this behaviour on
_Remove this hint: these checkboxes can be checked like this: [x]_

- [ ] Android device

### I am using

- [ ] cordova
- [ ] ionic

#### OS versions
Android 4.4.4

### I've checked these
- [ ] It happens on a fresh Cordova CLI project as well.
- [ ] I'm waiting for `deviceready` to fire.
- [ ] My JavaScript has no errors (`window.onerror` catches nothing).
- [ ] I'm using the latest cordova library, Android SDK, Xcode, etc.

**Comment by pbakondy** [comment]
Check README

Notice: the content of phoneNumber is unreliable (see this and this article). Sometimes phoneNumber is only an empty string.
