### ISSUE TITLE
cordova-plugin-sim Plugin not getting device Id in android 6.0

### ISSUE THREAD

**Issue by Gobi09** [pbakondy/cordova-plugin-sim#27]
cordova-plugin-sim Plugin not getting device Id in android 6.0

it shows all the values except Device Id in Android V6.0.

I am using this code in App.js:

angular.module('starter', ['ionic','ngCordova'])
.run(function($ionicPlatform) {
  $ionicPlatform.ready(function() {
document.addEventListener("deviceready", onDeviceReady, false);
function onDeviceReady() {
  window.plugins.sim.getSimInfo(successCallback, errorCallback);
}
function successCallback(result) {
  alert(JSON.stringify(result));
}
function errorCallback(error) {
  alert(JSON.stringify(error));
}

    if(window.cordova && window.cordova.plugins.Keyboard) {
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);
      cordova.plugins.Keyboard.disableScroll(true);
    }
    if(window.StatusBar) {
      StatusBar.styleDefault();
    }
  });
})

// But its showing all the value in lower version of Android phones. 

### I'm seeing this behaviour on

- [ ] iOS device
- [ ] iOS simulator
- [x ] Android device
- [ ] Android emulator

### I am using

- [x] cordova
- [x ] ionic
- [ ] PhoneGap
- [ ] PhoneGap Developer App
- [ ] Intel XDK
- [ ] Intel App Preview
- [ ] Telerik
- [ ] Other:

#### Hardware models
asus zenfone 2 laser 

#### OS versions
Android  6.0

### So how can we reproduce this?

Provide the used components versions (cordova, ionic, etc).

Provide the steps to reproduce the issue.

Provide files, sources if available.

**Comment by pbakondy** [comment]
permissions?

https://github.com/pbakondy/cordova-plugin-sim/blob/master/README.md#android-60-permissions

**Comment by Gobi09** [comment]
Thank you. 

I got it. Its working now...
Thanks lot

**Comment by pedro2911** [comment]
hello i have error with ios, not is working, the return is empty
