### ISSUE TITLE
Check Mobile Data enabled

### ISSUE THREAD

**Issue by pallaviMN** [pbakondy/cordova-plugin-sim#29]
Can i check the information for dual sim, in case of 2 sim in the android? Can i get information of both?
Is there any another approach for android CDMA?
Is there any way to check which sim is using mobile data in case of dual sim?

Regards
Pallavi M N

**Comment by pbakondy** [comment]
Please check latest release: v1.3.0

I would be happy to see here the sim plugin response of your device. It helps me to test and develop this plugin.
