### ISSUE TITLE
Usage code snippet 

### ISSUE THREAD

**Issue by Vasanth19** [pbakondy/cordova-plugin-sim#3]
Great work.. can you please share the usage code snippet? It would be greatly helpful.

**Comment by pbakondy** [comment]
You can find it in README under Usage section.

**Comment by Vasanth19** [comment]
Thanks..Does this return phone number only android? What about IOS?

**Comment by pbakondy** [comment]
Phone number is only Android

**Comment by Vasanth19** [comment]
Thanks for the quick response...is there any way we can validate the phone number for ios?  what are your suggestions.
Should I only rely on authenticating IOS user by sending validation code via SMS..Is this the only way to check the user's valid phone number in ios?

**Comment by pbakondy** [comment]
You should ask the user to enter his/her own phone number.
It is valid on Android too because the phoneNumber field can be empty or wrong.
Sending the validation code to this number is the only way to check the phone number validity.

**Comment by Vasanth19** [comment]
Thanks a lot.
