### ISSUE TITLE
Dual SIM info 

### ISSUE THREAD

**Issue by pointdeveloper** [pbakondy/cordova-plugin-sim#30]
### Expected behaviour
 There are a lot of devices that support more than one SIM. The plugin my return an object or array with info for all the SIMs

### Actual behaviour
Currently the SIM info is for one sim only.

- [ #] Android device

### I am using

- [ #] cordova
- [ #] ionic 2

#### Hardware models
YU YUREKA 

#### OS versions
Android 5.1.1

### I've checked these
- [ #] It happens on a fresh Cordova CLI project as well.
- [ ] I'm waiting for `deviceready` to fire.
- [ ] My JavaScript has no errors (`window.onerror` catches nothing).
- [ ] I'm using the latest cordova library, Android SDK, Xcode, etc.

### So how can we reproduce this?
Provide the used components versions (cordova, ionic, etc).
I used Ionic 2 along with Ionic native extensions.

**Comment by pbakondy** [comment]
Hi pointdeveloper,

please check latest version 1.3.0

I would be happy to see here the sim plugin response of your device. It helps me to test and develop this plugin.

thanks

**Comment by cormorano71** [comment]
I have an Android 4.4.2 dual sim ( NGM Forward Xtreme ).
I get all data of first sim and when I switch off first sim I get cached data of first sim or nothing.
In all the case I can't get info about second sim.

First sim switched off ret values
{
  "carrierName": "",
  "countryCode": "",
  "mcc": "",
  "mnc": "",
  "deviceId": "1234567890123456",
  "callState": 0,
  "dataActivity": 0,
  "networkType": 0,
  "phoneType": 1,
  "simState": 0,
  "isNetworkRoaming": false,
  "deviceSoftwareVersion" : "78"
}

**Comment by pbakondy** [comment]
Check https://github.com/pbakondy/cordova-plugin-sim#under-the-hood

Multiple sim handling requires Android API 22

**Comment by edukondalu123** [comment]
Hi @pbakondy,

My latest version of the plugin **cordova-plugin-sim** is 1.3.2
and 
my API Level 22, Lollipop 5.1.
I am not able to get multiple sims info. How can i get it?
Please help

**Comment by pbakondy** [comment]
you have to request permission first

**Comment by edukondalu123** [comment]
Oh..ok k
I am getting upto the cards label but not cards info...I thought i already have request permission

**Comment by edukondalu123** [comment]
See the below response of mine...
![screenshot_2017-01-04-15-41-02](https://cloud.githubusercontent.com/assets/20127057/21639535/98f124fa-d296-11e6-8714-98e2c53b9e60.png)

**Comment by edukondalu123** [comment]
See below pic for more info about my issue

![siminfo](https://cloud.githubusercontent.com/assets/20127057/21639817/23520078-d298-11e6-9a75-4870feda5025.JPG)

**Comment by edukondalu123** [comment]
Could u please assist me @pbakondy ?
Is it clear? or do u need more info?
Please...

**Comment by pbakondy** [comment]
Try latest release: v1.3.3
I adjusted the API level requirements.

**Comment by edukondalu123** [comment]
Thank you so much.... @pbakondy

**Comment by LVSMix** [comment]
How can I access phoneNumber in dual sim? Aparently I cant see the phoneNumber Attribute in cards array? @pbakondy

**Comment by astutesoftware** [comment]
@pbakondy phone Numbers are not written on the SIM Cards, You need to set it using an iphone (easiest method) or via stock android or a SIM writer utility.
