### ISSUE TITLE
Unable to get windows IMEI

### ISSUE THREAD

**Issue by k-srikanth** [pbakondy/cordova-plugin-sim#31]
Hi,

I am unable to get imei of my windows device,Actual response as
 ""carrierName":"Idea","countryCode":"","mcc":"","mnc":"","isCellularDataEnabled":"False","isCellularDataRoamingEnabled":"False","IsNetworkAvailable":"True","isWiFiEnabled":"True"}".

Please help me to resolve the issue.

Thanks & Regards,
Srikanth

**Comment by pbakondy** [comment]
Getting IMEI is an Android-only feature.
