### ISSUE TITLE
its not fetching the phone number

### ISSUE THREAD

**Issue by ajay121193** [pbakondy/cordova-plugin-sim#33]
### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead. Provide a log message if relevant

### I'm seeing this behaviour on
_Remove this hint: these checkboxes can be checked like this: [x]_

- [ ] iOS device
- [ ] iOS simulator
- [x] Android device
- [ ] Android emulator

### I am using

- [x] cordova
- [x] ionic
- [ ] PhoneGap
- [ ] PhoneGap Developer App
- [ ] Intel XDK
- [ ] Intel App Preview
- [ ] Telerik
- [ ] Other:

#### Hardware models
Example: Samsung Galaxy S6, iPhone 6s

#### OS versions
Example: Android 4.4.2, iOS 9.2

### I've checked these
- [ ] It happens on a fresh Cordova CLI project as well.
- [ ] I'm waiting for `deviceready` to fire.
- [ ] My JavaScript has no errors (`window.onerror` catches nothing).
- [ ] I'm using the latest cordova library, Android SDK, Xcode, etc.

### So how can we reproduce this?
Provide the used components versions (cordova, ionic, etc).

Provide the steps to reproduce the issue.

Provide files, sources if available.

**Comment by ajay121193** [comment]
this plugin not fetching the number

callState: 0
carrierName: "Reliance"
countryCode: "in"
dataActivity: 0
deviceId: "354799068449031"
deviceSoftwareVersion: "01"
isNetworkRoaming: false
mcc: "405"
mnc: "18"
networkType: 0
phoneNumber: ""
phoneType: 1
simSerialNumber: "8991184084050019607"
simState: 5
subscriberId: "405180040801960"


this is the object it returns the phonenumber feild is blank

**Comment by pbakondy** [comment]
The phonenumber field may be empty, please check the README.

Which Android API are you using? What is the version of Android of your
device?
