### ISSUE TITLE
[FEATURE] Request for email address from sim

### ISSUE THREAD

**Issue by rolinger** [pbakondy/cordova-plugin-sim#36]
### Expected behaviour

For Android (maybe windows), but I don't think possible on iOS, can email be extracted from sim info as well?  This plugin manages to do it from Android but it has limiations and returns nothing on other devices:  [DeviceInformationPlugin](https://github.com/vliesaputra/DeviceInformationPlugin)

It might not be SIM specific but the info is pertinent and sim related, the above plugin states:  E-mail/Phone number used by apps listed in your Settings > Accounts & Sync list

### Actual behaviour
Tell us what happens instead. Provide a log message if relevant

### I'm seeing this behaviour on

- [ ] iOS device
- [ ] iOS simulator
- [x] Android device
- [ ] Android emulator

### I am using

- [x] cordova
- [x] ionic
- [ ] PhoneGap
- [ ] PhoneGap Developer App
- [ ] Intel XDK
- [ ] Intel App Preview
- [ ] Telerik
- [ ] Other:

#### Hardware models
Example: Samsung Galaxy S6, iPhone 6s

#### OS versions
Example: Android 4.4.2, iOS 9.2

### I've checked these
- [ ] It happens on a fresh Cordova CLI project as well.
- [ ] I'm waiting for `deviceready` to fire.
- [ ] My JavaScript has no errors (`window.onerror` catches nothing).
- [ ] I'm using the latest cordova library, Android SDK, Xcode, etc.

### So how can we reproduce this?
Provide the used components versions (cordova, ionic, etc).

Provide the steps to reproduce the issue.

Provide files, sources if available.

**Comment by pbakondy** [comment]
Well, that feature uses a different Android API: AccountManager
https://developer.android.com/reference/android/accounts/AccountManager.html
It requires a new permission: GET_ACCOUNTS

This is not related to SIM.
There is no reason to add this feature to sim plugin.

If you are not satisfied with DeviceInformationPlugin try this one:
https://github.com/polychrom/cordova-android-accountmanager

**Comment by rolinger** [comment]
Yeah, wasn't certain it was related.  Closing this out and will refer to the one you mentioned.  However, I am opening another issue on pulling sim info in a moment.
