### ISSUE TITLE
Returned Obj missing keys.

### ISSUE THREAD

**Issue by rolinger** [pbakondy/cordova-plugin-sim#38]
### Expected behaviour
Returned object is missing fields.  Plugin docs state the return object should also have these keys - whether the values can be extracted or not (I think) is a different issue.  but i should at least see the entire Object (as stated in the docs) correct?
```
  "phoneNumber": "",
  "deviceId": "",
  "simSerialNumber": "",
  "subscriberId": "",
```

### Actual behaviour
My result object is as follows, though it is returning carrierName, seems the actual carrier can't be extracted from my phone.

```
Object {
   callState:0
   carrierName:""
   countryCode:"us"
   dataActivity:0
   isNetworkRoaming:false
   mcc:"310"
   mnc:"260"
   networkType:13
   phoneCount:1
   phoneType:1
   simState:5
}
```
### I'm seeing this behaviour on
- [ ] iOS device
- [ ] iOS simulator
- [x] Android device
- [ ] Android emulator

### I am using

- [x] cordova
- [x] ionic
- [ ] PhoneGap
- [ ] PhoneGap Developer App
- [ ] Intel XDK
- [ ] Intel App Preview
- [ ] Telerik
- [ ] Other:

#### Hardware models
Samsung Galaxy 5S

#### OS versions
Android 6

### I've checked these
- [ ] It happens on a fresh Cordova CLI project as well.
- [ ] I'm waiting for `deviceready` to fire.
- [ ] My JavaScript has no errors (`window.onerror` catches nothing).
- [x] I'm using the latest cordova library, Android SDK, Xcode, etc.

### So how can we reproduce this?
Provide the used components versions (cordova, ionic, etc).
Cordova 6.0
Ionic 1.7.14 (intentionally not upgrading to 2.0 yet)
cordova-plugin-sim 1.3.0

Provide the steps to reproduce the issue.

Provide files, sources if available.

**Comment by pbakondy** [comment]
Check permissions
https://github.com/pbakondy/cordova-plugin-sim#android-60-permissions

**Comment by rolinger** [comment]
yup...it was a permissions issue.  got it resolved.  Last question: is there away to set sim permissions in the config.xml/AndroidManifest.xml file?  I am using the cordova-plugin-diagnostics to add a bunch of permission for device settings but don't readily see an option for accessing the sim.

ie: 
```
    <config-file target="AndroidManifest.xml" parent="/*">
        <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    </config-file>
```

**Comment by pbakondy** [comment]
Sure, check this:
https://github.com/pbakondy/cordova-plugin-sim/blob/master/plugin.xml#L31

**Comment by rolinger** [comment]
sweet....great plugin.  and excellent support for it.  much appreciated.
