### ISSUE TITLE
Need call back in requestReadPermission.

### ISSUE THREAD

**Issue by rolinger** [pbakondy/cordova-plugin-sim#39]
### Expected behaviour

Is there any way to get a callback within requestReadPermission?  The setTimeout() works but its not an ideal situation  Something similar to how cordova-plugin-diagnostics requests permissions for various features.

I am doing this for a chained set of promises to step through app initialization to get user permissions but the native behavior of sim.requestReadPermission is relying on $timeout - or is there another method for sim?:

```
  function getPermissions(){
    var q = $q.defer();
    var statuses = {};
    window.plugins.sim.requestReadPermission(function(status) {                
      console.log('sim: '+status);
      statuses['sim'] = status;
      $timeout(function(){ cordova.plugins.diagnostic.requestContactsAuthorization(function(status){
        console.log('accounts: '+status);
        statuses['accounts'] = status;
        cordova.plugins.diagnostic.requestLocationAuthorization(function(status){
          console.log('gps: '+status);
          statuses['gps'] = status;
          q.resolve(statuses);
        }) ;
      });
      },5000) ;
    });
    return q.promise;
  }
```
### Actual behaviour

Tell us what happens instead. Provide a log message if relevant
### I'm seeing this behaviour on

_Remove this hint: these checkboxes can be checked like this: [x]_
- [ ] iOS device
- [ ] iOS simulator
- [ ] Android device
- [ ] Android emulator
### I am using
- [ ] cordova
- [ ] ionic
- [ ] PhoneGap
- [ ] PhoneGap Developer App
- [ ] Intel XDK
- [ ] Intel App Preview
- [ ] Telerik
- [ ] Other:
#### Hardware models

Example: Samsung Galaxy S6, iPhone 6s
#### OS versions

Example: Android 4.4.2, iOS 9.2
### I've checked these
- [ ] It happens on a fresh Cordova CLI project as well.
- [ ] I'm waiting for `deviceready` to fire.
- [ ] My JavaScript has no errors (`window.onerror` catches nothing).
- [ ] I'm using the latest cordova library, Android SDK, Xcode, etc.
### So how can we reproduce this?

Provide the used components versions (cordova, ionic, etc).

Provide the steps to reproduce the issue.

Provide files, sources if available.

**Comment by pbakondy** [comment]
done, see #43

**Comment by morganrallen** [comment]
I'd suggest closing this issue and opening two news ones requesting this feature for iOS and Windows Phone.

**Comment by pbakondy** [comment]
There is no permission request on iOS or Windows Phone

**Comment by morganrallen** [comment]
Oh yeah! Perfect!
