### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by r23h** [pbakondy/cordova-plugin-sim#4]
Do you have a example for use cordova plugin sim?

Thanks

**Comment by r23h** [comment]
Do you have a example for use cordova plugin sim?

Thanks

**Comment by pbakondy** [comment]
Read the README
https://github.com/pbakondy/cordova-plugin-sim#usage

**Comment by r23h** [comment]
i Try this:

    onDeviceReady: function() {
        app.receivedEvent('deviceready');
		
		function successCallback() {
			alert(JSON.parse(xjson));
		}
		function errorCallback() {
			alert("erro");
		}
		
		var xjson = window.plugins.sim.getSimInfo(successCallback, errorCallback);
    },

**Comment by pbakondy** [comment]
try this way:

```
onDeviceReady: function() {
    app.receivedEvent('deviceready');

    function successCallback(result) {
        alert(result);
    }
    function errorCallback(error) {
        alert(error);
    }

    window.plugins.sim.getSimInfo(successCallback, errorCallback);
},
```

**Comment by r23h** [comment]
Works well.

Thanks.

**Comment by Siwebst** [comment]
Hi Peter,
I'm trying to use your plugin in phonegap buld. I don't know how to make it work in my html-jquery-phonegap combination. Please for your help..
Adam

I have done so:

Androidmanifest.xml
  <uses-permission android:name="android.permission.READ_PHONE_STATE" />

config.xml
??

index.html
<script src="phonegap.js"></script>
<script src="sim/www/sim.js"></script>


function onDeviceReady() {
  window.plugins.powerManagement.acquire();
  window.plugins.sim.getSimInfo(successCallback, errorCallback);
}
 
function successCallback(result) {alert(result);}
function errorCallback(error) {alert(error);}

**Comment by MahdiSMIDA** [comment]
https://codesundar.com/phonegap-tutorial/get-sim-information-using-phonegap-apache-cordova/
