### ISSUE TITLE
Not getting IMEI in Android 6.0

### ISSUE THREAD

**Issue by juanmlf** [pbakondy/cordova-plugin-sim#40]
### Expected behaviour

Im not getting the proper info of the device. My code is this:

// check permission
function hasReadPermission() {
  window.plugins.sim.hasReadPermission(function(){
    //console.log("Tiene permisos para obtener sim");
  }, function(){
    requestReadPermission();
  });
}

// request permission
function requestReadPermission() {
  // no callbacks required as this opens a popup which returns async
  window.plugins.sim.requestReadPermission();
}

function getIMEI(){
  hasReadPermission();
  window.plugins.sim.getSimInfo(function(result){
    imei = result.deviceId;
  }, function(error){
    console.log(error);
  })
}
### Actual behaviour

What i get on result is:
{
  carrierName: "", 
  countryCode: "", 
  mcc: "", 
  mnc: "", 
  callState: 0,
  dataActivity: 0,
  isNetworkRoaming: false,
  networkType: 0,
  phoneType: 0,
  simState: 6
}

i debugged it and i have read permissions. I know some of these information is unknown, but i dont understand why im not getting the rest of it.
### I'm seeing this behaviour on
- [ ] iOS device
- [ ] iOS simulator
- [x] Android device
- [ ] Android emulator
### I am using
- [ ] cordova
- [ ] ionic
- [x] PhoneGap
- [ ] PhoneGap Developer App
- [ ] Intel XDK
- [ ] Intel App Preview
- [ ] Telerik
- [ ] Other:
#### Hardware models

Example: Tablet Xperia Z4 (No SIM card)
#### OS versions

Example: Android 6.0.1
### I've checked these
- [ ] It happens on a fresh Cordova CLI project as well.
- [x] I'm waiting for `deviceready` to fire.
- [x] My JavaScript has no errors (`window.onerror` catches nothing).
- [x] I'm using the latest cordova library, Android SDK, Xcode, etc.

**Comment by pbakondy** [comment]
How do you want to receive SIM information when your device has no SIM card?
