### ISSUE TITLE
is compatibe with version 4 of ios?

### ISSUE THREAD

**Issue by srsarcasmo** [pbakondy/cordova-plugin-sim#41]
I have trouble ios version 4 and I wonder if this version works or not to use another version as 10.2; Thanks for your answers

**Comment by pbakondy** [comment]
I tested only with iOS 8+.
It should work with iOS 4 but I am not able test. It is a 6 year old version.

**Comment by srsarcasmo** [comment]
thanks pbakondy, if the Gillen know how to fix this and other plugins in version 4 of ios please tell me;
