### ISSUE TITLE
iOS 10 issue, requestReadPermission is undefined.

### ISSUE THREAD

**Issue by rolinger** [pbakondy/cordova-plugin-sim#42]
### Expected behaviour
Should load fine, but it is not

### Actual behaviour
Tell us what happens instead. Provide a log message if relevant
Verson 1.3.0 sim is loaded into ios environment, deploying to iOS simulator iPhone 6 (iOS 10.0).

Getting error on: `window.plugins.sim.requestReadPermission` - says its not a function and is undefined.  It is being referenced after $ionicPlatform.ready is called.  However, this all works just fine on Android.

- [ ] iOS device
- [ x] iOS simulator
- [ ] Android device
- [ ] Android emulator

### I am using

- [x ] cordova
- [x ] ionic
- [ ] PhoneGap
- [ ] PhoneGap Developer App
- [ ] Intel XDK
- [ ] Intel App Preview
- [ ] Telerik
- [ ] Other:

#### Hardware models
Example: Samsung Galaxy S6, iPhone 6s

#### OS versions
Example: Android 4.4.2, iOS 9.2

### I've checked these
- [ ] It happens on a fresh Cordova CLI project as well.
- [ ] I'm waiting for `deviceready` to fire.
- [ ] My JavaScript has no errors (`window.onerror` catches nothing).
- [ ] I'm using the latest cordova library, Android SDK, Xcode, etc.

### So how can we reproduce this?
Provide the used components versions (cordova, ionic, etc).

Provide the steps to reproduce the issue.

Provide files, sources if available.

**Comment by pbakondy** [comment]
You dont have to use requestReadPermission on iOS.
This is Android only feature.

**Comment by rolinger** [comment]
ah, ok...will give it shot and post.  thanks

**Comment by rolinger** [comment]
yup...fixed.  Thanks
