### ISSUE TITLE
contextcompat.checkselfpermission not working

### ISSUE THREAD

**Issue by PremkumarAgrawal** [pbakondy/cordova-plugin-sim#44]
Hey @pbakondy I am facing error while building my app, at this line, in sim.java file at line number 233,

ContextCompat.checkSelfPermission(this.cordova.getActivity(), type));

**Comment by pbakondy** [comment]
not enough information

what is the error? environment? etc

**Comment by PremkumarAgrawal** [comment]
After hitting ionic run android 
I am getting following response on command prompt,

`F:\A_LHS_Projects\DynamicApp\DA_Code\DynamicApp_V2\platforms\android\src\com\pbakondy\Sim.java:233: error: cannot find symbol
      ContextCompat.checkSelfPermission(this.cordova.getActivity(), type));
                   ^
  symbol:   method checkSelfPermission(Activity,String)
  location: class ContextCompat

Note: Some input files use or override a deprecated API.

 FAILED

Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.


BUILD FAILED

Total time: 13.068 secs

Error: Error code 1 for command: cmd with args: /s,/c,"F:\A_LHS_Projects\DynamicApp\DA_Code\DynamicApp_V2\platforms\android\gradlew cdvBuildDebug -b F:\A_LHS_Projects\DynamicApp\DA_Code\DynamicApp_V2\platforms\android\build.gradle -Dorg.gradle.daemon=true -Pandroid.useDeprecatedNdk=true"



F:\A_LHS_Projects\DynamicApp\DA_Code\DynamicApp_V2>`

**Comment by PremkumarAgrawal** [comment]
Hey @pbakondy  did you understood the issue..

**Comment by pbakondy** [comment]
Did you install Android requirements?
https://github.com/pbakondy/cordova-plugin-sim#requirements

**Comment by PremkumarAgrawal** [comment]
@pbakondy  I have following support files of Android SDK installed
![capture](https://cloud.githubusercontent.com/assets/9786096/20624880/87809654-b335-11e6-8d0e-a133b0a13a3c.PNG)

**Comment by pbakondy** [comment]
What is the version of Android Support Library?
Please run `Android SDK Manager` and install latest packages.
Which SDK are you using?

**Comment by PremkumarAgrawal** [comment]
@pbakondy My Android SDK version is 6.0 (API 23)

`Android Support Library 23.2.1
![capture](https://cloud.githubusercontent.com/assets/9786096/20625194/b951f8c4-b337-11e6-9f53-96a9c3b9e2dd.PNG)
`

**Comment by pbakondy** [comment]
As I see Android Support Library is not installed yet

**Comment by pbakondy** [comment]
Ok, let's try something else.
I will make a few code changes, could you try it for me by installing it
from github?

**Comment by PremkumarAgrawal** [comment]
Yaa Sure... @pbakondy

**Comment by pbakondy** [comment]
Please try install the latest:
```
cordova plugin rm cordova-plugin-sim
cordova plugin add https://github.com/pbakondy/cordova-plugin-sim.git
```

**Comment by PremkumarAgrawal** [comment]
Should i run both the commands

**Comment by PremkumarAgrawal** [comment]
Hey @pbakondy have some urgent work..
will try later and get back to you...

Thanks for your instant support....

**Comment by pbakondy** [comment]
Yes, both commands
The first one removes the installed plugin from npm, the second one installs the latest code

**Comment by PremkumarAgrawal** [comment]
Hey @pbakondy  I installed SIM plugin successfully, & its working finely. Thanks for your support..

**Comment by bkiruthiga** [comment]
Hi. what changes have you made in the code. I am facing the same issue.. please mention the changes, it will be useful for me.
Thanks in advance
