### ISSUE TITLE
iOS device, undefined is not an object (evaluating 'window.plugins.sim.getSimInfo)

### ISSUE THREAD

**Issue by eparlier** [pbakondy/cordova-plugin-sim#45]
### Expected behaviour
Works on Android, breaks on iOS at window.plugins.sim.getSimInfo(onSimSuccess, onSimError);

### I'm seeing this behaviour on

- [x ] iOS device
- [ ] iOS simulator
- [ ] Android device
- [ ] Android emulator

### I am using

- [ x] cordova
- [ ] ionic
- [ ] PhoneGap
- [ ] PhoneGap Developer App
- [ ] Intel XDK
- [ ] Intel App Preview
- [ ] Telerik
- [ ] Other:

#### Hardware models
iPAD Pro (2016)

#### OS versions
 iOS 10.1.1

### I've checked these
- [x ] It happens on a fresh Cordova CLI project as well.
- [ x] I'm waiting for `deviceready` to fire.
- [x ] My JavaScript has no errors (`window.onerror` catches nothing).
- [x ] I'm using the latest cordova library, Android SDK, Xcode, etc.

### So how can we reproduce this?
install on iOS device

Provide the steps to reproduce the issue.
install on iOS device

Provide files, sources if available.

window.plugins.sim.getSimInfo(onSimSuccess, onSimError);

function onSimSuccess(__res){  	
	console.log('SIM RES', __res);	  		
}

function onSimError(__error){
	console.log('SIM RES', __error);	  		
}

Getting the error : undefined is not an object (evaluating 'window.plugins.sim.getSimInfo)

**Comment by pbakondy** [comment]
Could you print out window.plugins and window.plugins.sim after deviceready?

Could you try to create a simple cordova project with this plugin only?

**Comment by eparlier** [comment]
Fixed it by doing some clean up and resintalled. The issue was on my end.

**Comment by ek-thaviti** [comment]
I also have same issue with ios 10.3 above.
When i print below code
alert(cordova.plugins.sim);
It gives **undefined**
Plz help me to solve this issue... @pbakondy
