### ISSUE TITLE
Android 4.4.4 issue with dual sim

### ISSUE THREAD

**Issue by ramesh-sarvatra** [pbakondy/cordova-plugin-sim#47]
### Expected behaviour
cards array should be listed.

### Actual behaviour
cards array is null

### I'm seeing this behaviour on
- [ ] Android device

### I am using

- [ ] cordova
- [ ] ionic

#### Hardware models
Example: Samsung Galaxy S6, iPhone 6s
Lenovo A6000

#### OS versions
Android 4.4.4

### I've checked these
- [ ] It happens on a fresh Cordova CLI project as well.
- [ ] My JavaScript has no errors (`window.onerror` catches nothing).
- [ ] I'm using the latest cordova library, Android SDK, Xcode, etc.

### So how can we reproduce this?
Cordova, ionic

**Comment by pbakondy** [comment]
It is not a bug.

Check README: this feature is supported with


   - SubscriptionManager (since API level 22)

**Comment by ramesh-sarvatra** [comment]
HI pbakondy,

Currently plugin showing the single sim information on device running on less than lollipop versions.
Could please add cards array on devices running on less than lollipop versions regardless of both sim inserted or single sim inserted?

**Comment by pbakondy** [comment]
No I cannot because this older Android version does not support it.

**Comment by ramesh-sarvatra** [comment]
Ok. Thanks!
