### ISSUE TITLE
window.plugins.sim.getSimInfo not triggering

### ISSUE THREAD

**Issue by edukondalu123** [pbakondy/cordova-plugin-sim#49]
I have installed the plugin **cordova-plugin-sim**. When i checked this **window.plugins.sim.getSimInfo(successCallback, errorCallback)**, it's not triggering at all. The code is not working after this line

### I'm seeing this behaviour on
- [ ] iOS device
- [ ] iOS simulator
- [x] Android device
- [ ] Android emulator

### I am using

- [ ] cordov
- [ ] ionic
- [ ] PhoneGap
- [x] PhoneGap Developer App
- [ ] Intel XDK
- [ ] Intel App Preview
- [ ] Telerik
- [ ] Other:

#### Hardware models
Example: Coolpad Note 3

#### OS versions
Example: Android 5.1

### I've checked these
- [x] It happens on a fresh Cordova CLI project as well.
- [x] I'm waiting for `deviceready` to fire.
- [x] My JavaScript has no errors (`window.onerror` catches nothing).
- [x] I'm using the latest cordova library, Android SDK, Xcode, etc.

**Comment by pbakondy** [comment]
I need more details. Code, logs, environment, versions, etc?

**Comment by edukondalu123** [comment]
Thanks for reply...
My phonegap version is 6.2.0

**Code:**
document.addEventListener('deviceready', onDeviceReady, false);
function onDeviceReady()
{
	window.plugins.sim.getSimInfo(successCallback, errorCallback);
}
function successCallback(result) {
	alert(JSON.stringify(result));
}
			 
function errorCallback(error) {
	alert(JSON.stringify(error));
}

**Comment by pbakondy** [comment]
do you have any JS error?
where are you running this code? android phone?

**Comment by edukondalu123** [comment]
I though no JS error. Yes running in android phone using phonegap develope app.

**Comment by edukondalu123** [comment]
If i have JS error, it won't work for this sharing plugin below

document.addEventListener('deviceready', onDeviceReady, false);
function onDeviceReady()
{
	window.plugins.socialsharing.share("title", null, null, "url_link");
	//window.plugins.sim.getSimInfo(successCallback, errorCallback);
}

But it's working for sharing pluing. 

Can u please tell why it is not working?

**Comment by pbakondy** [comment]
yes, check this answer:
https://github.com/pbakondy/cordova-plugin-sim/issues/12#issuecomment-173531191

**Comment by edukondalu123** [comment]
Thanks a bunch @pbakondy really. You solved my issue.
Yes it is not working with phonegap developer app then i checked in my real android machine.
It's working fine.
Thank you so much...

**Comment by ek-thaviti** [comment]
Same issue happend in **ios 10.3 above**. Checked in real device.
May i get your attention @pbakondy 
Thank you...

**Comment by ETAPANG** [comment]
Hi,
Please I have the same issue with **cordova-plugin-sim**. In the apk generate and deploy in my phone is the not working. 
**I'm seeing this behaviour on**
- Android Device (apg generated by cordova)
**I am using**
- PhoneGap

This is the JascriptCode

**Comment by ETAPANG** [comment]
Sorry this is JavaScript Code

> var app = {
    // Application Constructor
    initialize: function() {
        this.bindEvents();
    },
    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    onDeviceReady: function() {
        app.receivedEvent('deviceready');
    },    
    receivedEvent: function(id) {       
		window.plugins.sim.getSimInfo(successCallback, errorCallback);
		//alert('Received Event= ' + id);	
    },	
	successCallback: function(result) {
		var doc = document.getElementById("simInfo");
		doc.innerHTML=JSON.stringify(result);
		alert(JSON.stringify(result));				
	},
	errorCallback: function(error) {		
		var doc = document.getElementById("simInfo");		
		alert(JSON.stringify(error));					
	 }

>

**Comment by ETAPANG** [comment]
I have Urgent Project with PhoneGap Cordova that request an access to SIM Card. 
Please help

Thank
