### ISSUE TITLE
Android : plugin is not returning phone number

### ISSUE THREAD

**Issue by seematalanki** [pbakondy/cordova-plugin-sim#5]
Using this plugin in Android phone , we are not able to get phone number, it just returns an empty string. Do we need to add any permission along with adding the plugin?

**Comment by pbakondy** [comment]
No other permossion required. Check the README.

**Comment by seematalanki** [comment]
this is the json we are getting when execute the plugin (window.plugins.sim.getSimInfo)
{"carrierName":"Vodafone IN","countryCode":"in","mcc":"404","mnc":"86","phoneNumber":"","callState":0,"dataActivity":4,"networkType":10,"phoneType":1,"simState":5}.
let us know if any thing else we need to try for getting the phone number.

**Comment by pbakondy** [comment]
Notice: the content of phoneNumber is unreliable (see this
<http://stackoverflow.com/questions/7922734/getting-reliable-msisdn-from-android-phone-voicemailnumber-line1number>
 and this
<http://stackoverflow.com/questions/25861064/retrieving-line1-number-from-telephonymanager-in-android>
 article).

**Comment by cricstarnitesh** [comment]
I am getting this. i tried in many phones . same result i am getting.
{"carrierName":"Jio 4G","countryCode":"in","mcc":"405","mnc":"861","callState":0,"dataActivity":3,"networkType":13,"phoneType":1,"simState":5,"isNetworkRoaming":false,"phoneCount":2}
