### ISSUE TITLE
Not getting Phone Number

### ISSUE THREAD

**Issue by NikicaAsanin** [pbakondy/cordova-plugin-sim#51]
I connect plugin and I get as I response a lot of data from phone but not the phone number. Can you tell me why?Thanks :)

**Comment by edukondalu123** [comment]
Have you checked issues which are closed. See below link
[https://github.com/pbakondy/cordova-plugin-sim/issues/50](https://github.com/pbakondy/cordova-plugin-sim/issues/50)
