### ISSUE TITLE
Failed to create App on Windows 10 UAP with IntelXDK

### ISSUE THREAD

**Issue by marcos-queiroz** [pbakondy/cordova-plugin-sim#53]
Hi, I tried to compile a project using intelXDK, but when trying to compile for Windows 10 UAP intelXDK gives me the following error: "Warning: Plugin SIM appears to be missing the windows platform support required for this build target. The API provided by this plugin may not work on the windows platform."

**Comment by pbakondy** [comment]
Windows 10 UAP means Windows 10 universal app platform.
This plugin currently supports only Windows Phone 7 and 8.
If you want you can build the support for this platform.
