### ISSUE TITLE
Not getting PhoneNumber

### ISSUE THREAD

**Issue by cricstarnitesh** [pbakondy/cordova-plugin-sim#55]
Getting everything only phone number, simSerialNumber,subscriberId is missing

### Actual behaviour
Tell us what happens instead. Provide a log message if relevant

### I'm seeing this behaviour on
_Remove this hint: these checkboxes can be checked like this: [x]_

- [ ] iOS device
- [ ] iOS simulator
- [x] Android device
- [ ] Android emulator

### I am using

- [x] cordova
- [ ] ionic
- [ ] PhoneGap
- [ ] PhoneGap Developer App
- [ ] Intel XDK
- [ ] Intel App Preview
- [ ] Telerik
- [ ] Other:

#### Hardware models
any android device

#### OS versions
Example: Android 6 above

working with Jquery

Provide the steps to reproduce the issue.

Provide files, sources if available.

**Comment by pbakondy** [comment]
Check #5
