### ISSUE TITLE
Dual-SIM not detected

### ISSUE THREAD

**Issue by moradec** [pbakondy/cordova-plugin-sim#56]
### Expected behaviour
Expected to get information about inserted cards calling "getSimInfo".

### Actual behaviour
Properties "cards", "activeSubscriptionInfoCount" and "activeSubscriptionInfoCountMax" are missing.

### I'm seeing this behaviour on
- [ x] Android device

### I am using
- [ x] cordova

#### Hardware models
Archos 50c Neon

#### OS versions
Android 4.4.2
cordova 5.1.1

### I've checked these
- [ x] It happens on a fresh Cordova CLI project as well.
- [ x] I'm waiting for `deviceready` to fire.
- [x ] My JavaScript has no errors (`window.onerror` catches nothing).

### So how can we reproduce this?
I am testing with several devices. All devices are above Android-Version 5 and the plugin is working. Just with this Dual-SIM device and Android 4.4.2 it seems to be a problem.

**Comment by pbakondy** [comment]
Properties "cards", "activeSubscriptionInfoCount" and "activeSubscriptionInfoCountMax" are provided by SubscriptionManager API.
SubscriptionManager API is available from Android API level 22.
Android 4.4.2 is API level 19

**Comment by akash-pal** [comment]
But i have this same problem on Redmi Note 3 which is currently running on Android Marshmallow. So frankly this issue is not closed. 

I only get information regarding the first sim.

**Comment by pbakondy** [comment]
Did you request permissions with requestReadPermission() ?

**Comment by akash-pal** [comment]
yes i did , then only i got the full information. I have another query. 

How to distinguish when User **Denies a permission** from when user ticks **"Never Ask Again" and then Denies**?

**Comment by pbakondy** [comment]
I never tested. Do you have a bug?

**Comment by akash-pal** [comment]
Well yes sort of. When I deny permission first time, the next time the "Never Ask again" options comes. If you tap of that option and deny then . The Permission Denied Message is showed in both cases. So there is no way to differentiate?
