### ISSUE TITLE
App freeze when I check permission

### ISSUE THREAD

**Issue by guilhermemauro** [pbakondy/cordova-plugin-sim#58]
When I'm trying check android permissions, my app freezes.

- [ ] iOS device
- [ ] iOS simulator
- [X] Android device
- [X] Android emulator

### I am using

- [X] cordova
- [ ] ionic
- [X] PhoneGap
- [ ] PhoneGap Developer App
- [ ] Intel XDK
- [ ] Intel App Preview
- [ ] Telerik
- [ ] Other:

#### Hardware models
Genymotion Nexus 4 (Android kitkat), Zuk z2 plus

#### OS versions
Android 4.4.4, Mokee 7.1.1

### I've checked these
- [ ] It happens on a fresh Cordova CLI project as well.
- [ ] I'm waiting for `deviceready` to fire.
- [X] My JavaScript has no errors (`window.onerror` catches nothing).
- [ ] I'm using the latest cordova library, Android SDK, Xcode, etc.

**Comment by pbakondy** [comment]
Try creating a single application with this plugin only and try again.
Let's exclude device-related issues.

**Comment by guilhermemauro** [comment]
After I requested permission, I can check permission without freeze.
