### ISSUE TITLE
Error while using plugin

### ISSUE THREAD

**Issue by atulkrajput** [pbakondy/cordova-plugin-sim#64]
Hi i am using this plugin for the first time to get the sim details for verification, No error but getting following error in log.
```
Could not find method android.telephony.TelephonyManager.getPhoneCount, referenced from method com.pbakondy.Sim.execute
VFY: unable to resolve virtual method 10659: Landroid/telephony/TelephonyManager;.getPhoneCount ()I
Could not find class 'android.telephony.SubscriptionManager', referenced from method com.pbakondy.Sim.execute
```

Using Android 7.1.1 [API 25]
Testing on Android emulator
cordova 6.2.3
`<uses-permission android:name="android.permission.READ_PHONE_STATE" />`

Can anyone please help.

Thanks.

**Comment by pbakondy** [comment]
Emulator has no sim card
