### ISSUE TITLE
Im not able to get the phone number.

### ISSUE THREAD

**Issue by johnpaulcm** [pbakondy/cordova-plugin-sim#66]
### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead. Provide a log message if relevant

### I'm seeing this behaviour on
_Remove this hint: these checkboxes can be checked like this: [x]_

- [ ] iOS device
- [ ] iOS simulator
- [x] Android device
- [ ] Android emulator

### I am using

- [x] cordova
- [x] ionic
- [ ] PhoneGap
- [ ] PhoneGap Developer App
- [ ] Intel XDK
- [ ] Intel App Preview
- [ ] Telerik
- [ ] Other:

#### Hardware models
Example: Samsung Galaxy S6, iPhone 6s

#### OS versions
Example: Android 4.4.2, iOS 9.2

### I've checked these
- [x] It happens on a fresh Cordova CLI project as well.
- [ ] I'm waiting for `deviceready` to fire.
- [ ] My JavaScript has no errors (`window.onerror` catches nothing).
- [ ] I'm using the latest cordova library, Android SDK, Xcode, etc.

### So how can we reproduce this?
Provide the used components versions (cordova, ionic, etc).

Provide the steps to reproduce the issue.

Provide files, sources if available.

**Comment by pbakondy** [comment]
check #50
