### ISSUE TITLE
how to get  SIM Information in ionic cordova app showing empty string "" not return mobile number

### ISSUE THREAD

**Issue by anuj-njoshi** [pbakondy/cordova-plugin-sim#76]
### Expected behaviour
Phone number should be shown 
### Actual behaviour
I used cordova-plugin-sim api for getting sim information.It's works fine with dual sim phone device but when i tried to single sim  device. It's shown all sim data except mobile number.   
### I'm seeing this behaviour on

- [ ] Android device

### I am using

- [ ] cordova
- [ ] ionic

#### Hardware models
Example: Samsung Galaxy S6, iPhone 6s

#### OS versions
Example: Android 6.4.2

### I've checked these
- [ ] It happens on a fresh Cordova CLI project as well.
- [ ] I'm waiting for `deviceready` to fire.
- [ ] My JavaScript has no errors (`window.onerror` catches nothing).
- [ ] I'm using the latest cordova library, Android SDK, Xcode, etc.

### So how can we reproduce this?
Provide the used components versions (cordova, ionic, etc).
I am using Ionic v1
Provide the steps to reproduce the issue.
I call   window.plugins.sim.getSimInfo(successCallback, errorCallback);
to retrieve sim data. 
Provide files, sources if available.
Referring https://www.npmjs.com/package/cordova-plugin-sim2

**Comment by pbakondy** [comment]
check #50
