### ISSUE TITLE
How can I get carrier name to a string

### ISSUE THREAD

**Issue by azn1viet** [pbakondy/cordova-plugin-sim#8]
function successCallback(result) {
            alert(result);//give me [object][object]
            alert(result['carrierName']);//give me 'Verizon'
            return result['carrierName'];//give me null
        }
        function errorCallback(error) {
            alert(error);
        }

       var dataCarrier =   window.plugins.carrier.getCarrierInfo(successCallback, errorCallback);

dataCarrier gives null, only alert works. How can I get carrier name to a string as dataCarrier

**Comment by pbakondy** [comment]
You want to use callbacks in a wrong way.

Try this code:

```js
var dataCarrier;

function successCallback(result) {
    alert(result);//give me [object][object]
    alert(result['carrierName']);//give me 'Verizon'
    dataCarrier = result['carrierName'];
}

function errorCallback(error) {
    alert(error);
}

window.plugins.carrier.getCarrierInfo(successCallback, errorCallback);
```

**Comment by azn1viet** [comment]
thanks, it works.
