### ISSUE TITLE
app can't access imei in android 10.

### ISSUE THREAD

**Issue by yinglight** [pbakondy/cordova-plugin-sim#88]
app can't access imei number in android 10.Because the mechanism of Android 10 has changed.

**Comment by mcendon** [comment]
I found the same problem in my app with android 10. 

This plugin has no maitenance since 3 years ago, i will try to fork it and adapt the plugin to support android api 29

**Comment by mcendon** [comment]
I found this: https://developer.android.com/about/versions/10/privacy/changes#non-resettable-device-ids
It's necessary to declare a special permission to access "non-resetteable" data like SIM and IMEI in android 10.
The only problem is that caution that advice: "Caution: Third-party apps installed from the Google Play Store cannot declare privileged permissions."
So, i dont know if we can obtain that data in android 10... it will be a question of test it and see if it works

**Comment by nyoumi** [comment]
any solution?

**Comment by cutechsupport** [comment]
Here also facing same problem, any solution?

**Comment by pbakondy** [comment]
https://developer.android.com/about/versions/10/privacy/changes

It will not work anymore
