### ISSUE TITLE
Rejected by Build.phonegap

### ISSUE THREAD

**Issue by sahabe1** [pbakondy/cordova-plugin-sim#9]
i have added plugin  in config.xml
<gap:plugin name="cordova-plugin-sim" version="1.0.2"/>
<gap:plugin name="cordova-plugin-sim"/>

both the time phunegap build rejected

plugin unsupported: cordova-plugin-sim

**Comment by PPOW-RGUPTA** [comment]
Faced same issue. build.phonegap.com rejected the code saying this plugin is not supported. Any insight or workaround would be great.

Thanks

**Comment by pbakondy** [comment]
I can not submit a plugin to Public Plugins on PhoneGap Build.

See: http://phonegap.com/blog/2015/09/04/public-plugin-deprecation-on-build/

This plugin can be found at http://cordova.apache.org/plugins/
